name: elementfold
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - sounddevice
  - matplotlib
  - pandas
  - numba
  - sympy
  - pytest
  - black
  - isort
