name: elementfold
channels:
  - pytorch         # official PyTorch builds
  - conda-forge     # wide ecosystem
  - nvidia
  - defaults
dependencies:
  # ---- core Python ----
  - python=3.11

#  # ---- PyTorch stack (CPU build) ----
#  - pytorch
#  - torchvision
#  - torchaudio
#  - cpuonly          # ensures the CPU variant is selected

  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1    # or 12.4 depending on your driver


  # ---- numerics / utils ----
  - numpy
  - scipy
  - numba
  - pandas
  - matplotlib
  - pillow
  - sympy

  # ---- dev & QA ----
  - pytest
  - black
  - isort

  # ---- audio IO (from conda-forge; avoids pip builds) ----
  - python-sounddevice   # sounddevice bindings (depends on portaudio)
  - pysoundfile          # convenient wav/flac loader (libsndfile)
  - portaudio            # runtime library for sounddevice
  - libsndfile           # runtime library for pysoundfile

  - pip
  - pip:
      # - some-pypi-only-package

